### PR TITLE
bump some dependencies

### PR DESCRIPTION
**Pull request by tacman**
I took a first pass at bumping the dependencies (including the phpflickr library!)

Tests fail, because the "name" attribute is missing.  But really tests should bump to phpunit 11, which I think now supports attributes.

Guzzle is outdated, but rather than update it, what do you think of switching to the Symfony HttpClient?

### CODE REVIEW

**Comment by samwilson** [comment]
I think all updates here are now done by #21, so this can be closed.

> Guzzle is outdated, but rather than update it, what do you think of switching to the Symfony HttpClient?

That sounds fine I guess, but I'm not sure what the difference would really be. The latest Guzzle release was six months ago, and it's a pretty stable project. What would be the advantage in using `symfony/http-client`?

**Comment by tacman** [comment]
Since this is a stand-alone application, there's really no benefit.

But if this were part of a bundle, then it would make sense that the user could choose their http client. I like Symfony's because of the logging and built-in retry and throttling.

**Comment by samwilson** [comment]
That's a good point.

PhpFlickr uses `carlos-mg89/oauth` to make HTTP requests, which uses [its own](https://github.com/carlos-mg89/PHPoAuthLib/blob/b267f5dd252750b247cf93d37ae6acc9c5734d14/src/OAuth/Common/Http/Client/ClientInterface.php) HTTP client; it'd be cool to make that injectable.

I must admit, I'm still not completely sure why you want to integrate this app into another app. Is the other app something general, or is it adding functionality that perhaps could be added here?

**Comment by tacman** [comment]
Having worked with this and your library for a while now, I have a better understanding.  A bundle is a good solution for me that incorporates some of the functionality here with my application.

So it's not integrating this app with another app, but integrating some of the functionality.  Anyway, I'll cherry-pick the stuff I need most into the bundle.

**Pull request closed without merging**
